[2023-12-25T07:45:56.130+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-02-07T00:00:00+00:00/task_id=Extract permission to 509
[2023-12-25T07:45:56.130+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-02-07T00:00:00+00:00/task_id=Extract permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-02-07T00:00:00+00:00/task_id=Extract'
[2023-12-25T07:45:56.270+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-02-07T00:00:00+00:00/task_id=Extract permission to 509
[2023-12-25T07:45:56.270+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-02-07T00:00:00+00:00/task_id=Extract permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-02-07T00:00:00+00:00/task_id=Extract'
[2023-12-25T07:45:56.352+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-02-07T00:00:00+00:00 [queued]>
[2023-12-25T07:45:56.370+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-02-07T00:00:00+00:00 [queued]>
[2023-12-25T07:45:56.371+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-25T07:45:56.756+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): Extract> on 2023-02-07 00:00:00+00:00
[2023-12-25T07:45:56.770+0000] {standard_task_runner.py:60} INFO - Started process 581 to run task
[2023-12-25T07:45:56.787+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'traffic_flow', 'Extract', 'scheduled__2023-02-07T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp2ur8odfp']
[2023-12-25T07:45:56.798+0000] {standard_task_runner.py:88} INFO - Job 76: Subtask Extract
[2023-12-25T07:45:56.901+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-25T07:45:57.057+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-02-07T00:00:00+00:00/task_id=Extract permission to 509
[2023-12-25T07:45:57.057+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-02-07T00:00:00+00:00/task_id=Extract permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-02-07T00:00:00+00:00/task_id=Extract'
[2023-12-25T07:45:57.058+0000] {task_command.py:423} INFO - Running <TaskInstance: traffic_flow.Extract scheduled__2023-02-07T00:00:00+00:00 [running]> on host b33131cfaa7f
[2023-12-25T07:45:57.556+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='traffic_flow' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-02-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-07T00:00:00+00:00'
[2023-12-25T07:45:57.558+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 31, in task_a_function
    csv_reader.read_data()
  File "/opt/airflow/dags/src/extract_data_source.py", line 10, in read_data
    with open(self.csv_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hp/Downloads/20181024_d1_0830_0900(2).csv'
[2023-12-25T07:45:57.584+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=traffic_flow, task_id=Extract, execution_date=20230207T000000, start_date=20231225T074556, end_date=20231225T074557
[2023-12-25T07:45:58.300+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 76 for task Extract ([Errno 2] No such file or directory: '/home/hp/Downloads/20181024_d1_0830_0900(2).csv'; 581)
[2023-12-25T07:45:58.344+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-25T07:45:58.433+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
