[2023-12-25T02:57:23.313+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: traffic_flow.Extract scheduled__2023-02-07T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
