[2023-12-25T07:45:33.912+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-01-27T00:00:00+00:00/task_id=Extract permission to 509
[2023-12-25T07:45:33.913+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-01-27T00:00:00+00:00/task_id=Extract permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-01-27T00:00:00+00:00/task_id=Extract'
[2023-12-25T07:45:34.103+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-01-27T00:00:00+00:00/task_id=Extract permission to 509
[2023-12-25T07:45:34.116+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-01-27T00:00:00+00:00/task_id=Extract permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-01-27T00:00:00+00:00/task_id=Extract'
[2023-12-25T07:45:34.254+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-01-27T00:00:00+00:00 [queued]>
[2023-12-25T07:45:34.307+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-01-27T00:00:00+00:00 [queued]>
[2023-12-25T07:45:34.308+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2023-12-25T07:45:34.426+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): Extract> on 2023-01-27 00:00:00+00:00
[2023-12-25T07:45:34.457+0000] {standard_task_runner.py:60} INFO - Started process 544 to run task
[2023-12-25T07:45:34.463+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'traffic_flow', 'Extract', 'scheduled__2023-01-27T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmphpke90c2']
[2023-12-25T07:45:34.470+0000] {standard_task_runner.py:88} INFO - Job 64: Subtask Extract
[2023-12-25T07:45:34.597+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-25T07:45:34.715+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-01-27T00:00:00+00:00/task_id=Extract permission to 509
[2023-12-25T07:45:34.716+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-01-27T00:00:00+00:00/task_id=Extract permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=traffic_flow/run_id=scheduled__2023-01-27T00:00:00+00:00/task_id=Extract'
[2023-12-25T07:45:34.717+0000] {task_command.py:423} INFO - Running <TaskInstance: traffic_flow.Extract scheduled__2023-01-27T00:00:00+00:00 [running]> on host b33131cfaa7f
[2023-12-25T07:45:35.175+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='traffic_flow' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-27T00:00:00+00:00'
[2023-12-25T07:45:35.177+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 31, in task_a_function
    csv_reader.read_data()
  File "/opt/airflow/dags/src/extract_data_source.py", line 10, in read_data
    with open(self.csv_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hp/Downloads/20181024_d1_0830_0900(2).csv'
[2023-12-25T07:45:35.214+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=traffic_flow, task_id=Extract, execution_date=20230127T000000, start_date=20231225T074534, end_date=20231225T074535
[2023-12-25T07:45:35.897+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 64 for task Extract ([Errno 2] No such file or directory: '/home/hp/Downloads/20181024_d1_0830_0900(2).csv'; 544)
[2023-12-25T07:45:35.935+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-25T07:45:36.143+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
