[2023-12-25T02:23:23.311+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-01-04T00:00:00+00:00 [queued]>
[2023-12-25T02:23:23.340+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-01-04T00:00:00+00:00 [queued]>
[2023-12-25T02:23:23.340+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2023-12-25T02:23:23.489+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): Extract> on 2023-01-04 00:00:00+00:00
[2023-12-25T02:23:23.520+0000] {standard_task_runner.py:60} INFO - Started process 10601 to run task
[2023-12-25T02:23:23.548+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'traffic_flow', 'Extract', 'scheduled__2023-01-04T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmprsjxwkp_']
[2023-12-25T02:23:23.564+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask Extract
[2023-12-25T02:23:23.716+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-25T02:23:24.191+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task Extract ((psycopg2.OperationalError) connection to server at "postgres" (172.19.0.2), port 5432 failed: could not fork new process for connection: Cannot allocate memory

(Background on this error at: https://sqlalche.me/e/14/e3q8); 10601)
[2023-12-25T02:23:24.237+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-25T02:23:27.624+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
